[buildPlans.CodeOnePiece]
family = "Code OnePiece"
spacing = "fixed"
serifs = "sans"
EXPORTGLYPHNAMES = false

# [buildPlans.CodeOnePiece.variants]
# inherits = "ss14"

[buildPlans.CodeOnePiece.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-interrupted-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "serifed-symmetric"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "crossing"
capital-r = "straight-bottom-right-serifed"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-unilateral-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "double-storey-hook-inward-serifed-serifless"
b = "toothless-rounded-serifless"
c = "unilateral-inward-serifed"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-serifed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "serifed-asymmetric"
k = "curly-serifless"
l = "serifed-flat-tailed"
m = "serifless"
n = "straight-serifless"
p = "eared-serifless"
q = "straight-serifless"
r = "hookless-top-serifed"
s = "unilateral-inward-serifed"
t = "flat-hook"
u = "toothless-rounded-serifless"
v = "straight-motion-serifed"
w = "cursive-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
zero = "tall-slashed"

[buildPlans.CodeOnePiece.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.CodeOnePiece.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.CodeOnePiece.weights.Bold]
shape = 800
menu = 800
css = 800

[buildPlans.CodeOnePiece.widths.normal]
shape = 525
menu  = 5
css   = "normal"
